---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# source("scripts/")
# source("scripts/")
# source("scripts/")
# source("scripts/")
# source("scripts/")
```

While the world seems to be in a standstill, we thought we would choose an aspect of many people's lives that serves as a constant: coffee. Coffee is a bridge for people to connect, so looking into it further to see who/where experiences coffee in different ways is very interesting to our group. Our goal is that through this project is to understand the different manners and individuals that consume coffee and how a simple cup of coffee can shape someone's habits.

The United States Department of Agriculture (USDA) collects data from agency activities which are then summarized into reports. The file we are going to explore consists of data about coffee bean production, export, import and consumption for every country by year. With this data, we can answer our questions about how coffee production and coffee culture is distributed around the world.

(summary paragraph)

(table)
(observations)

(chart 1 purpose)
(chart)
(observations)

(chart 2 purpose)
(chart)
(observations)

(chart 3 purpose)
(chart)
(observations)